inductive Color where
  | white
  | black
  deriving Repr, DecidableEq, Inhabited

def Color.opposite : Color → Color
  | white => black
  | black => white

inductive PieceType where
  | pawn | knight | bishop | rook | queen | king
  deriving Repr, DecidableEq

structure Piece where
  color : Color
  type  : PieceType
  deriving Repr, DecidableEq

abbrev File := Fin 8
abbrev Rank := Fin 8

structure Square where
  file : File
  rank : Rank
  deriving Repr, DecidableEq

/-- Board is defined as a function from `Square` to `Option Piece` -/
def Board := Square → Option Piece

/-- Empty board -/
def Board.empty : Board := fun _ => none

/-- Update a square on the board -/
def Board.update (b : Board) (sq : Square) (p : Option Piece) : Board :=
  fun s => if s == sq then p else b s

structure CastlingRights where
  whiteKingside  : Bool
  whiteQueenside : Bool
  blackKingside  : Bool
  blackQueenside : Bool

structure Move where
  fromSq    : Square
  toSq      : Square
  promotion : Option PieceType

structure GameState where
  board       : Board
  turn        : Color
  castling    : CastlingRights
  enPassant   : Option Square
  numMove     : Nat
  halfMoves   : Nat
  valid       : Bool
  messages    : List String
  history     : List Move

/-- Return the square with an offset of `(df, dr)` from square `sq` (`df` is along file, `dr` is along rank) -/
def Square.offsetSquare (sq : Square) (df dr : Int) : Option Square :=
  let f := sq.file.val + df
  let r := sq.rank.val + dr
  if h : 0 ≤ f ∧ f < 8 ∧ 0 ≤ r ∧ r < 8 then
    some { file := ⟨f.toNat, by grind⟩, rank := ⟨r.toNat, by grind⟩ }
  else
    none

/-- Return all moves generated by offsets from square `startSq` -/
def GameState.generateStepMoves (state : GameState) (startSq : Square) (offsets : List (Int × Int))
    : List Move :=
  offsets.filterMap fun (df, dr) =>
    match startSq.offsetSquare df dr with
    | none => none
    | some targetSq =>
      match state.board targetSq with
      | some p => if p.color == state.turn then none else some (Move.mk startSq targetSq none)
      | none   => some (Move.mk startSq targetSq none)

/-- Return all valid slide moves in a direction -/
def Board.slideMove (board : Board) (color : Color) (startSq currentSq : Square) (df dr : Int) (fuel : Nat)
    : List Move :=
  match fuel with
  | 0 => []
  | n + 1 =>
    match currentSq.offsetSquare df dr with
    | none => []
    | some nextSq =>
      match board nextSq with
      | none => -- empty; continue moving
        (Move.mk startSq nextSq none) :: (slideMove board color startSq nextSq df dr n)
      | some p =>
        if p.color != color then
          [Move.mk startSq nextSq none] -- Opponent piece; capture and stop
        else
          [] -- Own piece; stop before it

/-- Get a list of all possible slide moves in all given directions -/
def GameState.generateSlideMoves (state : GameState) (sq : Square) (directions : List (Int × Int))
    : List Move :=
  directions.flatMap fun (df, dr) => state.board.slideMove state.turn sq sq df dr 7

/-- Return all valid knight moves for knight at square `sq` -/
def GameState.knightMoves (state : GameState) (sq : Square) : List Move :=
  let offsets := [(1, 2), (2, 1), (-1, 2), (-2, 1), (1, -2), (2, -1), (-1, -2), (-2, -1)]
  state.generateStepMoves sq offsets

/-- Return all valid rook moves for rook at square `sq` -/
def GameState.rookMoves (state : GameState) (sq : Square) : List Move :=
  let directions := [(0, 1), (0, -1), (1, 0), (-1, 0)]
  state.generateSlideMoves sq directions

/-- Return all valid bishop moves for bishop at square `sq` -/
def GameState.bishopMoves (state : GameState) (sq : Square) : List Move :=
  let directions := [(1, 1), (1, -1), (-1, 1), (-1, -1)]
  state.generateSlideMoves sq directions

/-- Return all valid queen moves for queen at square `sq` -/
def GameState.queenMoves (state : GameState) (sq : Square) : List Move :=
  let directions := [(0, 1), (0, -1), (1, 0), (-1, 0), (1, 1), (1, -1), (-1, 1), (-1, -1)]
  state.generateSlideMoves sq directions

/-- Return pawn move from `fromSq` to `toSq`, along with promotion if possible -/
def GameState.makePawnMovesAndPromotion (state : GameState) (fromSq toSq : Square) : List Move :=
  let isProm := match state.turn with
    | .white => toSq.rank == 7
    | .black => toSq.rank == 0
  if isProm then
    [ Move.mk fromSq toSq (some PieceType.queen),
      Move.mk fromSq toSq (some PieceType.rook),
      Move.mk fromSq toSq (some PieceType.bishop),
      Move.mk fromSq toSq (some PieceType.knight) ]
  else
    [ Move.mk fromSq toSq none ]

/-- Return all valid pawn moves for pawn at square `sq` -/
def GameState.pawnMoves (state : GameState) (sq : Square) : List Move :=
  let dir := match state.turn with | .white => 1 | .black => -1
  let startRank := match state.turn with | .white => 1 | .black => 6
  let singlePushMoves :=
    match sq.offsetSquare 0 dir with
    | none => [] -- not possible
    | some targetSq =>
      match state.board targetSq with
      | none => state.makePawnMovesAndPromotion sq targetSq
      | some _ => []
  let doublePushMoves :=
    if sq.rank == startRank then
      match sq.offsetSquare 0 dir, sq.offsetSquare 0 (2 * dir) with
      | some step1, some step2 =>
        match state.board step1, state.board step2 with
        | none, none => [Move.mk sq step2 none]
        | _, _ => []
      | _, _ => [] -- not possible
    else []
  let captureOffsets := [(-1, dir), (1, dir)]
  let captureMoves := captureOffsets.flatMap fun (df, dr) =>
    match sq.offsetSquare df dr with
    | none => []
    | some targetSq =>
      -- Normal Capture
      let normalCap := match state.board targetSq with
        | some p => if p.color != state.turn then state.makePawnMovesAndPromotion sq targetSq else []
        | none => []
      -- En Passant Capture
      let epCap := match state.enPassant with
        | some epSq => if targetSq == epSq then [Move.mk sq targetSq none] else []
        | none => []
      normalCap ++ epCap
  -- Combine all valid pawn moves
  singlePushMoves ++ doublePushMoves ++ captureMoves
