/-
Authors: Malhar A. Patel
-/

inductive Color where
  | white
  | black
  deriving Repr, DecidableEq, Inhabited

def Color.opposite : Color → Color
  | white => black
  | black => white

inductive PieceType where
  | pawn | knight | bishop | rook | queen | king
  deriving Repr, DecidableEq

structure Piece where
  color : Color
  type  : PieceType
  deriving Repr, DecidableEq

abbrev File := Fin 8
abbrev Rank := Fin 8

structure Square where
  file : File
  rank : Rank
  deriving Repr, DecidableEq

/-- Board is defined as a function from `Square` to `Option Piece` -/
def Board := Square → Option Piece

/-- Empty board -/
def Board.empty : Board := fun _ => none

/-- Update a square on the board -/
def Board.update (b : Board) (sq : Square) (p : Option Piece) : Board :=
  fun s => if s == sq then p else b s

structure NormalMove where
  fromSq : Square
  toSq   : Square

structure PawnPromotionMove where
  fromSq    : Square
  toSq      : Square
  promotion : PieceType

structure PawnEnPassantMove where
  fromSq      : Square
  enPassantSq : Square

inductive Castle where
  | kingside
  | queenside

structure CastlingRights where
  whiteKingside  : Bool
  whiteQueenside : Bool
  blackKingside  : Bool
  blackQueenside : Bool

inductive Move where
  | normal    (m : NormalMove)
  | castle    (m : Castle)
  | promotion (m : PawnPromotionMove)
  | enPassant (m : PawnEnPassantMove)

structure GameState where
  board       : Board
  turn        : Color
  castling    : CastlingRights
  enPassantSq : Option Square
  numMove     : Nat := 0
  halfMoves   : Nat
  valid       : Bool := true
  messages    : List String := []
  history     : List NormalMove := []

open GameState Color NormalMove Move PieceType Castle

/-- Return the square with an offset of `(df, dr)` from square `sq` (`df` is along file, `dr` is along rank) -/
def Square.offsetSquare (sq : Square) (df dr : Int) : Option Square :=
  let f := sq.file.val + df
  let r := sq.rank.val + dr
  if h : 0 ≤ f ∧ f < 8 ∧ 0 ≤ r ∧ r < 8 then
    some { file := ⟨f.toNat, by grind⟩, rank := ⟨r.toNat, by grind⟩ }
  else
    none

/-- Return all moves generated by offsets from square `startSq` -/
def GameState.generateStepMoves (state : GameState) (startSq : Square) (offsets : List (Int × Int))
    : List Move :=
  offsets.filterMap fun (df, dr) =>
    match startSq.offsetSquare df dr with
    | none => none
    | some targetSq =>
      match state.board targetSq with
      | some p => if p.color == state.turn then none else some <| normal ⟨startSq, targetSq⟩
      | none   => some <| normal ⟨startSq, targetSq⟩

/-- Return all valid slide moves in a direction -/
def Board.slideMove (board : Board) (color : Color) (startSq currentSq : Square) (df dr : Int) (fuel : Nat)
    : List Move :=
  match fuel with
  | 0 => []
  | n + 1 =>
    match currentSq.offsetSquare df dr with
    | none => []
    | some nextSq =>
      match board nextSq with
      | none => -- empty; continue moving
        (normal ⟨startSq, nextSq⟩) :: (slideMove board color startSq nextSq df dr n)
      | some p =>
        if p.color != color then
          [normal ⟨startSq, nextSq⟩] -- Opponent piece; capture and stop
        else
          [] -- Own piece; stop before it

/-- Get a list of all possible slide moves in all given directions -/
def GameState.generateSlideMoves (state : GameState) (sq : Square) (directions : List (Int × Int))
    : List Move :=
  directions.flatMap fun (df, dr) => state.board.slideMove state.turn sq sq df dr 7

/-- Return all valid knight moves for knight at square `sq` -/
def GameState.knightMoves (state : GameState) (sq : Square) : List Move :=
  let offsets := [(1, 2), (2, 1), (-1, 2), (-2, 1), (1, -2), (2, -1), (-1, -2), (-2, -1)]
  state.generateStepMoves sq offsets

/-- Return all valid rook moves for rook at square `sq` -/
def GameState.rookMoves (state : GameState) (sq : Square) : List Move :=
  let directions := [(0, 1), (0, -1), (1, 0), (-1, 0)]
  state.generateSlideMoves sq directions

/-- Return all valid bishop moves for bishop at square `sq` -/
def GameState.bishopMoves (state : GameState) (sq : Square) : List Move :=
  let directions := [(1, 1), (1, -1), (-1, 1), (-1, -1)]
  state.generateSlideMoves sq directions

/-- Return all valid queen moves for queen at square `sq` -/
def GameState.queenMoves (state : GameState) (sq : Square) : List Move :=
  let directions := [(0, 1), (0, -1), (1, 0), (-1, 0), (1, 1), (1, -1), (-1, 1), (-1, -1)]
  state.generateSlideMoves sq directions

/-- Return all valid pawn moves for pawn at square `sq` -/
def GameState.pawnMoves (state : GameState) (sq : Square) : List Move :=
  singlePushMoves ++ doublePushMoves ++ captureMoves    
  where
    dir := match state.turn with | .white => 1 | .black => -1
    singlePushMoves :=
      match sq.offsetSquare 0 dir with
      | none => [] -- not possible
      | some targetSq =>
        match state.board targetSq with
        | none => makePawnMovesAndPromotion sq targetSq
        | some _ => []
    startRank := match state.turn with | .white => 1 | .black => 6
    doublePushMoves :=
      if sq.rank == startRank then
        match sq.offsetSquare 0 dir, sq.offsetSquare 0 (2 * dir) with
        | some step1, some step2 =>
          match state.board step1, state.board step2 with
          | none, none => [normal ⟨sq, step2⟩]
          | _, _ => []
        | _, _ => [] -- not possible
      else []
    captureOffsets := [(-1, dir), (1, dir)]
    captureMoves := captureOffsets.flatMap fun (df, dr) =>
      match sq.offsetSquare df dr with
      | none => []
      | some targetSq =>
        -- Normal Capture
        let normalCap := match state.board targetSq with
          | some p => if p.color != state.turn then makePawnMovesAndPromotion sq targetSq else []
          | none => []
        -- En Passant Capture
        let epCap := match state.enPassantSq with
          | some epSq => if targetSq == epSq then [enPassant ⟨sq, targetSq⟩] else []
          | none => []
        normalCap ++ epCap
    makePawnMovesAndPromotion (fromSq toSq : Square) :=
      let isProm := match state.turn with
        | .white => toSq.rank == 7
        | .black => toSq.rank == 0
      if isProm then
        [ promotion ⟨fromSq, toSq, queen⟩,
          promotion ⟨fromSq, toSq, rook⟩,
          promotion ⟨fromSq, toSq, bishop⟩,
          promotion ⟨fromSq, toSq, knight⟩ ]
      else
        [ normal ⟨fromSq, toSq⟩ ]

def GameState.offsetPiece (state : GameState) (sq : Square) (df dr : Int)
    : Option Piece := do
  state.board <| ← sq.offsetSquare df dr

def GameState.hasCastlingRights (state : GameState) (col : Color) (side : Castle)
    : Bool :=
  match col, side with
  | white, kingside  => state.castling.whiteKingside
  | black, queenside => state.castling.blackQueenside
  | black, kingside  => state.castling.blackKingside
  | white, queenside => state.castling.whiteQueenside

/-- Return all valid king moves (does not check for checks) -/
def GameState.kingMoves (state : GameState) (sq : Square) : List Move :=
  normalMoves ++ kingsideMoves ++ queensideMoves
  where
    normalMoves := state.generateStepMoves sq
      [(0, 1), (0, -1), (1, 0), (-1, 0), (1, 1), (1, -1), (-1, 1), (-1, -1)]
    kingsideMoves := if state.hasCastlingRights state.turn kingside then
        match state.offsetPiece sq 1 0, state.offsetPiece sq 2 0 with
        | none, none => [castle kingside]
        | _, _ => []
      else []
    queensideMoves := if state.hasCastlingRights state.turn queenside then
        match state.offsetPiece sq (-1) 0, state.offsetPiece sq (-2) 0 with
        | none, none => [castle queenside]
        | _, _ => []
      else []

/-- Return all valid moves for piece `p` at square `sq` in game -/
def GameState.generateMovesFor (state : GameState) (sq : Square) (p : Piece)
    : List Move :=
  if p.color != state.turn then []
  else match p.type with
    | pawn   => state.pawnMoves sq
    | knight => state.knightMoves sq
    | bishop => state.bishopMoves sq
    | rook   => state.rookMoves sq
    | queen  => state.queenMoves sq
    | king   => state.kingMoves sq

/-- List of all squares on chessboard -/
def allSquares : List Square :=
  (List.finRange 8).flatMap fun f =>
    (List.finRange 8).map fun r =>
      { file := f, rank := r }

/-- Generate all pseudo-legal moves in game -/
def GameState.generateAllPseudoLegalMoves (state : GameState) : List Move :=
  allSquares.flatMap fun sq =>
    match state.board sq with
    | some p => state.generateMovesFor sq p
    | none   => []

/-- Update castling rights based on piece `p` moving from `fromSq` to `toSq` -/
def CastlingRights.updateCastlingRights (rights : CastlingRights) (fromSq toSq : Square) (p : Piece)
    : CastlingRights :=
  match p.type, p.color with
  | .king, .white => { rights with whiteKingside := false, whiteQueenside := false}
  | .king, .black => { rights with blackKingside := false, blackQueenside := false }
  | _, _ => checkRook toSq <| checkRook fromSq rights
  where
  checkRook (sq : Square) (cr : CastlingRights) : CastlingRights :=
    if      sq.rank == 0 ∧ sq.file == 7 then { cr with whiteKingside := false }
    else if sq.rank == 0 ∧ sq.file == 0 then { cr with whiteQueenside := false }
    else if sq.rank == 7 ∧ sq.file == 7 then { cr with blackKingside := false }
    else if sq.rank == 7 ∧ sq.file == 0 then { cr with blackQueenside := false }
    else    cr
